// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: grpc/protocol/app/go_demo/go_demo.proto

package go_demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
type GetUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId     string `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	ReqSource string `protobuf:"bytes,2,opt,name=req_source,json=reqSource,proto3" json:"req_source,omitempty"`
	Uid       int32  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protocol_app_go_demo_go_demo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protocol_app_go_demo_go_demo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protocol_app_go_demo_go_demo_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *GetUserRequest) GetReqSource() string {
	if x != nil {
		return x.ReqSource
	}
	return ""
}

func (x *GetUserRequest) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId     string `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	ReqSource string `protobuf:"bytes,2,opt,name=req_source,json=reqSource,proto3" json:"req_source,omitempty"`
	Uid       int32  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Age       int32  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *GetUserReply) Reset() {
	*x = GetUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protocol_app_go_demo_go_demo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReply) ProtoMessage() {}

func (x *GetUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protocol_app_go_demo_go_demo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReply.ProtoReflect.Descriptor instead.
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return file_grpc_protocol_app_go_demo_go_demo_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserReply) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *GetUserReply) GetReqSource() string {
	if x != nil {
		return x.ReqSource
	}
	return ""
}

func (x *GetUserReply) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetUserReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserReply) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_grpc_protocol_app_go_demo_go_demo_proto protoreflect.FileDescriptor

var file_grpc_protocol_app_go_demo_go_demo_proto_rawDesc = []byte{
	0x0a, 0x27, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x61, 0x70, 0x70, 0x2f, 0x67, 0x6f, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x67, 0x6f, 0x5f, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x72,
	0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x22, 0x7c, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65,
	0x71, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x71, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67,
	0x65, 0x32, 0x3b, 0x0a, 0x0c, 0x47, 0x6f, 0x44, 0x65, 0x6d, 0x6f, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x2b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x16,
	0x5a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67,
	0x6f, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_protocol_app_go_demo_go_demo_proto_rawDescOnce sync.Once
	file_grpc_protocol_app_go_demo_go_demo_proto_rawDescData = file_grpc_protocol_app_go_demo_go_demo_proto_rawDesc
)

func file_grpc_protocol_app_go_demo_go_demo_proto_rawDescGZIP() []byte {
	file_grpc_protocol_app_go_demo_go_demo_proto_rawDescOnce.Do(func() {
		file_grpc_protocol_app_go_demo_go_demo_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_protocol_app_go_demo_go_demo_proto_rawDescData)
	})
	return file_grpc_protocol_app_go_demo_go_demo_proto_rawDescData
}

var file_grpc_protocol_app_go_demo_go_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_protocol_app_go_demo_go_demo_proto_goTypes = []interface{}{
	(*GetUserRequest)(nil), // 0: GetUserRequest
	(*GetUserReply)(nil),   // 1: GetUserReply
}
var file_grpc_protocol_app_go_demo_go_demo_proto_depIdxs = []int32{
	0, // 0: GoDemoAction.GetUser:input_type -> GetUserRequest
	1, // 1: GoDemoAction.GetUser:output_type -> GetUserReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_protocol_app_go_demo_go_demo_proto_init() }
func file_grpc_protocol_app_go_demo_go_demo_proto_init() {
	if File_grpc_protocol_app_go_demo_go_demo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_protocol_app_go_demo_go_demo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protocol_app_go_demo_go_demo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_protocol_app_go_demo_go_demo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_protocol_app_go_demo_go_demo_proto_goTypes,
		DependencyIndexes: file_grpc_protocol_app_go_demo_go_demo_proto_depIdxs,
		MessageInfos:      file_grpc_protocol_app_go_demo_go_demo_proto_msgTypes,
	}.Build()
	File_grpc_protocol_app_go_demo_go_demo_proto = out.File
	file_grpc_protocol_app_go_demo_go_demo_proto_rawDesc = nil
	file_grpc_protocol_app_go_demo_go_demo_proto_goTypes = nil
	file_grpc_protocol_app_go_demo_go_demo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GoDemoActionClient is the client API for GoDemoAction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoDemoActionClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error)
}

type goDemoActionClient struct {
	cc grpc.ClientConnInterface
}

func NewGoDemoActionClient(cc grpc.ClientConnInterface) GoDemoActionClient {
	return &goDemoActionClient{cc}
}

func (c *goDemoActionClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error) {
	out := new(GetUserReply)
	err := c.cc.Invoke(ctx, "/GoDemoAction/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoDemoActionServer is the server API for GoDemoAction service.
type GoDemoActionServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserReply, error)
}

// UnimplementedGoDemoActionServer can be embedded to have forward compatible implementations.
type UnimplementedGoDemoActionServer struct {
}

func (*UnimplementedGoDemoActionServer) GetUser(context.Context, *GetUserRequest) (*GetUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterGoDemoActionServer(s *grpc.Server, srv GoDemoActionServer) {
	s.RegisterService(&_GoDemoAction_serviceDesc, srv)
}

func _GoDemoAction_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoDemoActionServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoDemoAction/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoDemoActionServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoDemoAction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GoDemoAction",
	HandlerType: (*GoDemoActionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _GoDemoAction_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/protocol/app/go_demo/go_demo.proto",
}
